server:
  port: 18089
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 604800
      persistent: true
      store-dir: "/../session"
      cookie:
        max-age: 604800
  tomcat:
    max-swallow-size: 20MB
  error:
    include-message: always
    whitelabel:
      enabled: false  # 기본 오류 페이지 비활성화
    include-stacktrace: never
    path: /error
    
springdoc:
  api-docs:
    path: /v3/api-docs   # API 문서 경로
  swagger-ui:
    path: /swagger-ui.html   # Swagger UI 경로
    tags-sorter: alpha
    operations-sorter: alpha
  version: v1.0.0
  packages-to-scan: com.example


          
spring:
  main:
    allow-bean-definition-overriding: true 
    
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      location: multipartlocation
      max-file-size: 10MB
      max-request-size: 20MB
  
  devtools:
    livereload:
      enabled: true
#    restart:   
#      enabled: false
  mvc:
    contentnegotiation:
      favor-parameter: true
    hiddenmethod:
      filter:
        enabled: true

    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
    pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:mysql://localhost:3306/dongil
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 30000
#      pool-name: MyHikariCP
#      max-lifetime: 2000000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1

  jackson:
    serialization:
      fail-on-empty-beans: false

  
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.*.dto
  mapper-locations: classpath:mappers/*.xml
  

logging:
  level:
    demo: error
#    org: 
#      mybatis: DEBUG
#      springframework: DEBUG
